Consolidate drive not found error messages
alcionai/corso pull request #3845
Opened 2023-07-18 22:28 UTC by pandeyabs

---

#### Does this PR need a docs update or release note?

- [ ] :white_check_mark: Yes, it's included
- [ ] :clock1: Yes, but in a later PR
- [ ] :no_entry: No

#### Type of change

- [ ] :sunflower: Feature
- [ ] :bug: Bugfix
- [ ] :world_map: Documentation
- [ ] :robot: Supportability/Tests
- [ ] :computer: CI/Deployment
- [ ] :broom: Tech Debt/Cleanup

#### Issue(s)

* #<issue>

#### Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

2023-07-18 22:53 UTC, ryanfkeepers requested changes

2023-07-18 22:53 UTC, ryanfkeepers commented on src/internal/m365/graph/errors.go
> +		f.Compare(string(FileNotFound)) {
I'm not comfortable with this change.  Even by graph api standards, calling a drive a file is outrageous.  How sure are we that we:
1. understand the conditions and context of the error.
2. will avoid unwanted collisions with non-drive file-not-found errors.
3. are not seeing a live graph api bug.

2023-07-18 22:53 UTC, ryanfkeepers commented on src/pkg/services/m365/api/users.go
> +		if !clues.HasLabel(err, graph.LabelsDriveNotFound) && !clues.HasLabel(err, graph.LabelsNoSharePointLicense) {
formatting should be consistent throughout
```suggestion
		if !clues.HasLabel(err, graph.LabelsDriveNotFound) &&
		    !clues.HasLabel(err, graph.LabelsNoSharePointLicense) {
```

2023-07-18 23:39 UTC, ryanfkeepers approved these changes
attempted a workaround in sync.  Unable to find it.  Moving forward with a short-term fix.

2023-07-19 00:46 UTC, pandeyabs commented
Closing this as a transient error. Will open an issue with graph/kiota http to expose underlying http response codes to graph api users.

2023-07-19 00:46 UTC, closed without merging