Increamental backups for Groups SharePoint
alcionai/corso pull request #4187
Opened 2023-09-05 10:06 UTC by meain

Manual test results

$ ./corso backup create groups --hide-progress --group 1899aa5f-7ada-4096-abeb-9e40fce544b9
go build -o corso
==================================================================================================
        WARNING!!! THIS IS A PRE-RELEASE COMMAND THAT MAY NOT FUNCTION PROPERLY, OR AT ALL
==================================================================================================

Logging to file: /home/meain/.cache/corso/logs/2023-09-05T08-41-10Z.log
Done

  ID                                    Bytes Uploaded  Items Uploaded  Items Skipped  Errors
  f51d4377-3304-45a5-9ef4-135597dbd6e0  116 kB          6               0              0

Completed Backups:
  ID                                    Started At            Duration      Status     Resource Owner
  f51d4377-3304-45a5-9ef4-135597dbd6e0  2023-09-05T08:41:17Z  9.424782882s  Completed  Teams Testing (meain)

$ ./corso backup create groups --hide-progress --group 1899aa5f-7ada-4096-abeb-9e40fce544b9
go build -o corso
==================================================================================================
        WARNING!!! THIS IS A PRE-RELEASE COMMAND THAT MAY NOT FUNCTION PROPERLY, OR AT ALL
==================================================================================================

Logging to file: /home/meain/.cache/corso/logs/2023-09-05T08-41-33Z.log
Done

  ID                                    Bytes Uploaded  Items Uploaded  Items Skipped  Errors
  4fbbd5c9-9e41-41c9-8485-ca4d40b93a6b  0 B             0               0              0

Completed Backups:
  ID                                    Started At            Duration      Status     Resource Owner
  4fbbd5c9-9e41-41c9-8485-ca4d40b93a6b  2023-09-05T08:41:39Z  8.258722251s  Completed  Teams Testing (meain)

---

#### Does this PR need a docs update or release note?

- [ ] :white_check_mark: Yes, it's included
- [x] :clock1: Yes, but in a later PR
- [ ] :no_entry: No

#### Type of change

- [x] :sunflower: Feature
- [ ] :bug: Bugfix
- [ ] :world_map: Documentation
- [ ] :robot: Supportability/Tests
- [ ] :computer: CI/Deployment
- [ ] :broom: Tech Debt/Cleanup

#### Issue(s)

* https://github.com/alcionai/corso/issues/3990

#### Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E (will be added later)

2023-09-05 17:24 UTC, ryanfkeepers requested changes

2023-09-05 17:24 UTC, ryanfkeepers commented on src/internal/m365/backup.go
> +	rp kinject.RestoreProducer,
Hmm, I have significant concerns about this pattern.  At large, it produces three smells: 1/ it couples the requirements of one service onto the design of _all_ providers and services; 2/ it requires an interface whose behavior is the _opposite_ of the current functions behavior, which is all kinds of confusing at a glance (it's only incidental that retrieving metadata is a "restore" behavior; meanwhile this func declaration now reads like, "this backup will restore data"); 3/ it goes against the established pattern of metadata collection production and passdown (ie: generically, at the top of the operation layer) by shifting _some_of the that code deep into backup creation.

I think the smells can be fixed up with a fairly minimal amount of work.  Mostly re-thinking how you approach the creation and handoff of this metadata.  High level, right now you're saying, "I'll get the metadata by handing the collection restorer into the backup".  Instead, how about, "I'll get the metadata by having the provider/service export an interface-compliant func for extra metadata retrieval"?

Something like this: 
* add a new func to `inject.BackupProducer` like `RetrieveMetadata(rp RestoreProducer, stuff...)`.  you'll probably want it to return a map[string]whatever to namespace by subservice or path, like the site ID.
* have m365/controller comply with this interface.
* in the controller func, switch on the service.  If it's groups, call into `collectSiteMetadata()` and any other necessary calls.  All other services return nil.
* call `RetrieveMetadata()` in `operations.produceManifestsAndMetadata()`
* extend the produceBackup with a new parameter, "additionalMetadata".  Or maybe make a struct to hold the two metadatas.  Pass the metadata produced in operations down into the backup production.

This way, you're solving the smells by: 1/ keeping apis more consistent with structures that all services use, 2/ ensuring the parameters passed into backup production make sense to backup behavior, 3/ consolidating ownership of the place where behavior is utilized (not necessarily where implementation is held, the behavior utilization is more important here) in a centralized spot.

2023-09-06 07:23 UTC, meain commented on src/internal/operations/test/group_test.go
> +	sel := selectors.NewGroupsRestore([]string{suite.its.site.ID})
Woops, my bad. This is still a stub.

2023-09-07 11:31 UTC, meain commented
Closing in favor of https://github.com/alcionai/corso/pull/4205

2023-09-07 11:31 UTC, closed without merging