relocates lists and associated relationship retrieval from M365
alcionai/corso pull request #4785
Opened 2023-12-02 08:27 UTC by HiteshRepo

---

#### Does this PR need a docs update or release note?
- [x] :no_entry: No

#### Type of change

- [x] :sunflower: Feature

#### Issue(s)
#4754

#### Test Plan

- [x] :muscle: Manual
- [x] :zap: Unit test
- [x] :green_heart: E2E

2023-12-04 16:56 UTC, ryanfkeepers approved these changes

2023-12-04 16:56 UTC, ryanfkeepers commented on src/pkg/services/m365/api/lists.go
> +func (c Lists) getListItems(ctx context.Context, siteID, listID string) ([]models.ListItemable, error) {
Can you please asdd TODO comments for all `get*Items` funcs that they need to be transferred to the current pager implementation?

2023-12-04 16:56 UTC, ryanfkeepers commented on src/pkg/services/m365/api/lists_test.go
> +					listID).
for our code standards, you can inline key:value pairs for readability.  Ex:
```suggestion
					"sites", siteID,
					"lists", listID).
```

2023-12-04 16:56 UTC, ryanfkeepers commented on src/pkg/services/m365/api/lists_test.go
> +			assert.Equal(t, 1, len(items))
This is a redundant pair of checks.  Only the `Equal` is useful.

2023-12-11 22:48 UTC, ryanfkeepers requested changes
@HiteshRepo there's been substantial code additions, including new logical processes, introduced to this PR since my last review.  Instead of adding those changes into this PR, please move them into a separate PR that I can review independently.

2023-12-12 19:25 UTC, HiteshRepo commented
> @HiteshRepo there's been substantial code additions, including new logical processes, introduced to this PR since my last review. Instead of adding those changes into this PR, please move them into a separate PR that I can review independently.

@ryanfkeepers the additions to this PR has only been approved PR merges which were already reviewed and approved. I am using this as a main branch for 'Sharepoint Lists'. The idea is to move backup and restore functionality altogether to the main branch.

2023-12-21 06:16 UTC, meain approved these changes
Approving as the individual PRs were separately looked at and approved.

2023-12-21 06:22 UTC, HiteshRepo commented
> Approving as the individual PRs were separately looked at and approved.

yes.all chained PRs have been approved and merged into this. Added them to the description.

2023-12-21 17:20 UTC, HiteshRepo commented
> > Approving as the individual PRs were separately looked at and approved.
> 
> yes.all chained PRs have been approved and merged into this. Added them to the description.

@ryanfkeepers can we merge this? The other PRs got chained from this and this has grown big as a result.

2023-12-22 05:04 UTC, meain commented
> ryanfkeepers can we merge this? The other PRs got chained from this and this has grown big as a result.

Let's go ahead and merge this as this PR only contains code from other PRs that have been already reviewed. Next time, let's make sure to merge them one-by-one instead of combining into a single PR and merging to main. This also help making bisect more useful.

2023-12-22 13:03 UTC, HiteshRepo commented
> > ryanfkeepers can we merge this? The other PRs got chained from this and this has grown big as a result.
> 
> Let's go ahead and merge this as this PR only contains code from other PRs that have been already reviewed. Next time, let's make sure to merge them one-by-one instead of combining into a single PR and merging to main. This also help making bisect more useful.

In case of regression(if any), this PR will cause difficult to hunt the cause. This has been broken down into multiple PRs of logical grouped changes.
- https://github.com/alcionai/corso/pull/4916
- https://github.com/alcionai/corso/pull/4917
- https://github.com/alcionai/corso/pull/4919
- https://github.com/alcionai/corso/pull/4920
- https://github.com/alcionai/corso/pull/4922
- https://github.com/alcionai/corso/pull/4923
- https://github.com/alcionai/corso/pull/4924

will close this once all of them are merged

2023-12-22 17:22 UTC, HiteshRepo commented
> > > ryanfkeepers can we merge this? The other PRs got chained from this and this has grown big as a result.
> > 
> > 
> > Let's go ahead and merge this as this PR only contains code from other PRs that have been already reviewed. Next time, let's make sure to merge them one-by-one instead of combining into a single PR and merging to main. This also help making bisect more useful.
> 
> In case of regression(if any), this PR will cause difficult to hunt the cause. This has been broken down into multiple PRs of logically grouped approved changes.
> 
> * [adds ListInfo details to SharepointInfo details #4916](https://github.com/alcionai/corso/pull/4916)
> * [adds list client apis and pagers #4917](https://github.com/alcionai/corso/pull/4917)
> * [adds list backup and restore handlers #4919](https://github.com/alcionai/corso/pull/4919)
> * [enables sharepoint to use lists backup handler for lists ops #4920](https://github.com/alcionai/corso/pull/4920)
> * [enable restore path creation for sharepoint lists #4922](https://github.com/alcionai/corso/pull/4922)
> * [enables sharepoint to use lists restore handler for lists ops #4923](https://github.com/alcionai/corso/pull/4923)
> * [cli changes for sharepoint lists #4924](https://github.com/alcionai/corso/pull/4924)
> 
> will close this once all of them are merged

closing this as all PRs have been merged

2023-12-22 17:22 UTC, closed without merging